# Generated by Django 6.0.3 on 2026-04-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
