# Generated by Django 6.0.3 on 2026-04-09 18:20

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')
    for row in Meeting.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
        
    LiveMeeting = apps.get_model('meetings', 'LiveMeeting')
    for row in LiveMeeting.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='livemeeting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
