# Generated by Django 6.0.3 on 2026-04-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
