# Generated by Django 6.0.3 on 2026-04-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_workspace_meeting_workspace_workspaceinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_meetings', to='meetings.workspace'),
        ),
    ]
