# Generated by Django 6.0.3 on 2026-04-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_livemeeting_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If false, only visible to creator'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If false, only visible to creator'),
        ),
        migrations.CreateModel(
            name='WorkspaceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='workspace_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
