# Generated by Django 6.0.3 on 2026-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_livemeeting_is_shared_meeting_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='livemeeting',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livemeeting',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livemeeting',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
