# Generated by Django 6.0.3 on 2026-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_livemeeting_duration_minutes_livemeeting_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
