# Generated by Django 6.0.3 on 2026-04-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_livemeeting_short_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livemeeting',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='livemeeting',
            name='password',
        ),
        migrations.RemoveField(
            model_name='livemeeting',
            name='short_id',
        ),
    ]
